### ISSUE TITLE
Email generator no working 

### ISSUE THREAD

**Issue by Deswer60871** [Mj23978/sam-assistant#1]
Traceback (most recent call last):
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 96, in <module>
    main()
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 87, in main
    mail_client = Emailnator()
                  ^^^^^^^^^^^^
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 22, in __init__
    "x-xsrf-token": self.client.cookies.get("XSRF-TOKEN")[:-3] + "=",
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Mj23978** [comment]
i embed the version of gpt4free and providers that works with it. 

what provider are you using for creating LLM ?

@Deswer60871
